import React from 'react'
import PropTypes from 'prop-types'
import { ApolloWrapper } from '../lib/apollo-wrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

/**
 * @param {Object} props
 * @param {React.ReactNode} props.children
 */
export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired
}
